#!/usr/bin/env bash

## Install ansible
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get install ansible

## pull ansible
sudo ansible-pull -U https://github.com/ThePrimeagen/ansible.git
