#!/usr/bin/env bash

## Install ansible
sudo apt-get install -y curl
sudo apt-get install -y git
sudo apt-get install -y software-properties-common
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y ansible

## pull ansible
sudo ansible-pull -U https://github.com/ThePrimeagen/ansible.git
